### ISSUE TITLE
querying via prometheus web interface results in "Error executing query: server returned HTTP status 400 Bad Request"

### ISSUE THREAD

**Issue by jodok** [brian-brazil/crate_adapter#1]
in the log output: `ERRO[0967] Failed to unmarshal body                      err="proto: bad wiretype for field remote.TimeSeries.Labels: got wiretype 0, want 2" source="server.go:375"`

reproduceable using prometheus 1.7.1 and master

**Comment by brian-brazil** [comment]
I can't reproduce this issue with a stock 1.7.1 and freshly built master.

Can you confirm that you followed the build instructions in the README?

**Comment by jodok** [comment]
yes, followed exactly the instructions. did this on my local apple. will try on a linux machine as well.

**Comment by brian-brazil** [comment]
Is the crate_adapter checked out under your GOPATH?

**Comment by jodok** [comment]
yes

**Comment by brian-brazil** [comment]
Wiretype 0 is an integer, 2 is a string or embedded message. So the wrong format data is being sent to the adapter. Line 375 is also write rather than read.

Can you share your Prometheus config, and confirm it's indeed 1.7.1 and not 1.6.x or earlier?

**Comment by jodok** [comment]
my bad. i yanked the wrong enpoint in the config /write instead of /read. works now
