### ISSUE TITLE
what is a primary key that makes sense?

### ISSUE THREAD

**Issue by jodok** [brian-brazil/crate_adapter#2]
to use the database in a reliable way we'd like to use a primary key.

in prometheus is it `ts, __name__`? rather not. is it `ts, __name__, [labels_for_that_metric]`?

one possibility is to create an l_hash field, store the SHA1 hash of the sorted labels and use them as part of the primary key that consists of ts, name, l_hash.

**Comment by brian-brazil** [comment]
The primary key in Prometheus for a timeseries is all the labels (of which the name is one), and the timeseries then identifies the point.

**Comment by jodok** [comment]
thanks for clarification, will propose schema in separate ticket
