### ISSUE TITLE
improved schema

### ISSUE THREAD

**Issue by jodok** [brian-brazil/crate_adapter#3]
here's the schema we propose:

```sql
CREATE TABLE "metrics" (
  "ts" TIMESTAMP,
  "name" STRING,
  "l_hash" STRING,
  "l" OBJECT(DYNAMIC),
  "value" DOUBLE,
  PRIMARY KEY ("ts", "name", "l_hash")
);
```

where `l_hash` is the SHA1 of the sorted labels (without `__name__`).

in contrast what we discussed earlier, the crate DOUBLE data type supports `NaN`, `Infinity` and `-Infinity`.

**Comment by brian-brazil** [comment]
I've tried this, but it doesn't appear workable as you get an error if you reference an non-existent labelname in a query: `SQLActionException[ColumnUnknownException: Column labels['lfoo'] unknown]`. The "l" prefix is also still needed on column names, as Crate doesn't allow underscores as the first character of column names.

**Comment by brian-brazil** [comment]
In fact this is a problem generally. Is there a way to not error out like this?

**Comment by brian-brazil** [comment]
That's done as close as I can reasonably get it.
