### ISSUE TITLE
crate_adapter doesn't properly close http connections

### ISSUE THREAD

**Issue by jodok** [brian-brazil/crate_adapter#6]
it seems crate_adapter isn't properly closing http connections but rather leaves them open.
after leaving it running for a couple of days/weeks we see connections to the crate cluster are piling up - easily 20k-40k. 
we're working on further details. 

note: this is still without the round-robin scheduling (waiting to build it due to #5)

**Comment by jodok** [comment]
additional information: we now and then see the following log message:
```
Aug 07 14:09:18 monitoring.b.fir.io prometheus[31119]: time="2017-08-07T14:09:18Z" level=warning msg="Error sending 100 samples to remote storage: context deadline exceeded" source="queue_manager.go:500"
```
it might be worth increasing the bulk size to 1000.

**Comment by brian-brazil** [comment]
Do you know if they're from read or writes?

**Comment by jodok** [comment]
so far we've been doing 99,9% writes only.

**Comment by brian-brazil** [comment]
From a quick test I can't reproduce this on either head or the previous version of this logic.

**Comment by jodok** [comment]
@seut ^

**Comment by jodok** [comment]
is it possible that the connections aren't properly closed if there is an issue with the inserts? e.g. a node is down? this week the test cluster was running out of disk space and no longer accepted inserts - which caused crate_adapter to go OOM. 
i'll do further tests and report here...
```
[Mon Aug  7 15:31:09 2017] Out of memory: Kill process 431 (crate_adapter) score 467 or sacrifice child
[Mon Aug  7 15:31:09 2017] Killed process 431 (crate_adapter) total-vm:4005684kB, anon-rss:3253032kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by brian-brazil** [comment]
I tested that and it was fine. Does `lsof` show the connections exist on both the adapter and crate end?

**Comment by jodok** [comment]
i can confirm that the side of the crate_adapter has only 22 connections per server open (8 crate servers). the amount of connections depends on how much remote shards it uses. it seems to be something else. closing or now.
